sonar.projectKey=costing-ui
sonar.projectName=Costing UI
sonar.projectVersion=1.0

# Source files
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/*.json
sonar.login=squ_2b8b7057ba81b98cc7906eebbf848dbd274b5d18
# Coverage report (only if you generate one)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# SonarQube server
sonar.host.url=http://localhost:9000

# Optional: If using authentication token
# sonar.login=your-token-here

sonar.sourceEncoding=UTF-8
