export const API_END_POINTS = {
    WHO_AM_I: '/whoami',
    LOGIN: '/auth/login',
    PARTS: '/parts',
    PART_DETAILS: '/parts/{partId}',
    VENDORS: '/vendors',
    VENDOR_DETAILS: '/vendors/{vendorId}',
    VENDOR_PARTS: '/vendors/{vendorId}/parts',
    PART_TYPES: '/parts/types',
    PART_UNITS: '/parts/units',
    CATEGORIES: '/categories',
    CATEGORIES_DETAILS: '/categories/{categoryId}',
    COST_FACTORS: '/cost-factors',
    COST_FACTORS_DETAILS: '/cost-factors/{id}',
    VENDOR_DOWNLOAD: '/vendors/download',
    PART_HISTORY:'/parts/cost-history',
    COST_CALCULATE: '/cost/calculate/{partId}',
    PART_DOWNLOAD: '/parts/download',
    BOM_DOWNLOAD:'/parts/bom/{partId}/download',
    USER:'/users',
    USER_ROLES:'/users/roles',
    USER_DETAILS:'/users/{userId}',

};